### ISSUE TITLE
Reviewing Object Drills

### ISSUE THREAD

**Issue by cabejackson** [TheoMakaurii/Object-Drills#1]
Hey, so objects are still kind of rough for me, so I'm redoing/reviewing the object-drills lesson. On line 45, did we ever get our array of objects to print correctly? I'm working on this whole assignment again now. I might send a pull request once i get more of it completed.

wow, nvm! I just had a typo lol

**Comment by TheoMakaurii** [comment]
Hi Caleb! 
Thats no problem at all.... I dont think you should have to request anything from me! You are listed as a full collaborator on this git. You should be able to pull, clone, or fork without a problem. 
My memory from that day is a little hazy but I do believe we got the character- job objects printing correctly.
Let me know if you need anything!
Theo.
